In [1]:
import numpy as np

In [2]:
#1--- Arithmetic Operations

In [3]:
a1= np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [4]:
#Size must be the same
a1+a2 #each corresponding number of a1 and a2 are added

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [13]:
#2--- BROADCASTING
#EK PARTICULAR VALUE KO MULTIPLE VALUES KO DENA FOR SOME OPERATION OR SOMETHING
#EG: ADDING 10 TOH ALL ARRAY ELEMENTS , JUST DO ARR+10.
#WE CAN DO THE SAME IN MATRIX TOO

In [15]:
arr=np.array([10,20,30,40])
arr+10

array([20, 30, 40, 50])

In [14]:
#3--- DEEP AND SHALLOW COPY

In [16]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice=a[:5]
slice= slice *10
slice

array([10, 20, 30, 40, 50])

In [23]:
#EVEN AFTER MAKING THE CHANGES TO A PART OF ARRAY AS SLICE THE ORIGINAL VALUES REMAIN UNTOUCHED
#THIS IS BECAUSE ARRAY CREATES A SEPARATE SPACE AND IF YOU SLICE IT WILL BE DONE ON A SEPARATE AREA THIS IS CALLED "SHALOW COPY"
#DEEP COPY ME SLICE ME CHANGES KAROGE TO ORIGINAL ME BHI SHOW HONGE
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
#BUT IF YOU COPY A ARRAY AND MAKE CHANGES TO THE COPIED ONE THEN THE CHANGES WILL BE SHOWN IN THE ORIGINAL ONE TOO
#THIS IS BECAUSE BOTH WILL BE STORED IN THE SAME LOCATION IN RAM
b=a
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
#BUT THIS WILL BE NOT DONE IF WE USE ".copy"
b=a.copy()
b[2]=40
b

array([99,  2, 40,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a #no change

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
#4--- MATRIX MULTIPLICATION

In [31]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])

In [32]:
#Multiplication (OG jo formula hota hai)
mat1@mat2 

array([[19, 22],
       [43, 50]])

In [33]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [34]:
#Transpose
mat1.T

array([[1, 3],
       [2, 4]])

In [35]:
#5--- ADVANCE ARRAY MANIPULATION:

In [37]:
#(i) STACKING ARRAY
#WE CANNOT STACK TWO MATRICES , ONLY VECTORS

In [38]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [39]:
np.vstack((a,b))
#VERTICALLY STACK HUA HAI MATLAB LENGTH BADHI HAI BY ADDING UP A ROW

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.hstack((a,b))
#HORIZONTALLY STACK HUA HAI BREADTH BADHI HAI

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
np.column_stack((a,b))
#column ke form me stack hue hain

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [42]:
#(ii) SPLITTING ARRAY

In [43]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
#HUMESHA EQUAL DIVISION HI HOTA HAI
#IMAGINE KARO HORIZONTAL LINE HAI BEECH SE KAAT DIYA TOH 2 LAMBE LAMBE PART HONGE , SAME WAISE HI
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [46]:
np.vsplit(c,2) #VERTICAL SPLIT KAR DIYA

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]