In [1]:
import numpy as np

In [3]:
#1---Basic array creation
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a=[1,2,3,4,'hi']
np.array(a)
#AS it stores the same datatype so every value is converted to string

array(['1', '2', '3', '4', 'hi'], dtype='<U21')

In [8]:
#One dimensional is called - Vector
#After 2D the vectors are called - Tensors
l=[[1,2],[3,4],[6,7]]
np.array(l)

array([[1, 2],
       [3, 4],
       [6, 7]])

In [9]:
#2---Array Generation Function
#np.arange(start,end,step)
ap=np.arange(1,11)
ap

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ap=np.arange(2,10,2)
ap

array([2, 4, 6, 8])

In [12]:
#zero creation
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [14]:
arr=np.zeros((3,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [16]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
#Equal spaced values from start to end
#linspace(st,end,no of values)
arr=np.linspace(1,8,3) 
arr

array([1. , 4.5, 8. ])

In [21]:
#3--- Random Generation Function
np.random.rand(5)

array([0.49608908, 0.62202791, 0.85704377, 0.64287749, 0.31972852])

In [22]:
#Random value from 0 to 5
np.random.randint(6)

0

In [24]:
#Random values from randint(st,end,no of values)
np.random.randint(10,20,5)

array([17, 15, 10, 17, 13], dtype=int32)

In [28]:
#4--- Array Attributes: (attribute ke aage bracket nahi lagta)
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [29]:
#Row-col shape
arr.shape

(3, 3)

In [30]:
#No of elements
arr.size

9

In [31]:
#Type
arr.dtype

dtype('int64')

In [32]:
#5--- Array Methods:
arr.min()

np.int64(1)

In [33]:
arr.max()

np.int64(8)

In [34]:
arr.sum()

np.int64(42)

In [36]:
#ROW/COL WISE SUM
#VERTICAL AXIS/COLUMN - 0 use
#HORIZONTAL AXIS/ROW - 1 use
np.sum(arr,axis=0) #column wise

array([11, 14, 17])

In [38]:
arr.mean()

np.float64(4.666666666666667)

In [40]:
#standard deviation
arr.std()

np.float64(2.2110831935702664)

In [41]:
#gives the index of max value
arr.argmax()

np.int64(8)

In [42]:
arr.argmin()

np.int64(0)

In [43]:
#6--- Reshaping and Resizing
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
#Reshaping the array in specific shape by row and col, but the multiplication of elements must the the same
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])