In [1]:
import numpy as np

In [2]:
#1--- NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
  arr[6]

np.int64(17)

In [5]:
#Slicing
#st:end+1
#5 tak likhogi to 4 tak jaayega
#default is 0
arr[1:5]

array([12, 13, 14, 15])

In [6]:
arr[:7]

array([11, 12, 13, 14, 15, 16, 17])

In [7]:
#3rd var is the steps you want to skip
arr[3::2]

array([14, 16, 18, 20])

In [8]:
#2--- NUMPY INDEXING AND SLICING IN MATRIX

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0] #targeting rows

array([1, 2, 3, 4, 5])

In [12]:
arr[0,0] #row,col

np.int64(1)

In [13]:
#Slicing rows and columns both
#mark the starting and ending of row and column then put them in the form:
#[rowst:rowend+1,colst:colend+1]
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [14]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
#Selecting only columns:
arr[:,2] #col 2

array([ 3,  8, 13, 18, 23, 28])

In [16]:
#3--- BOOLEAN INDEXING

In [17]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
bool_index= arr%2==0 #looping over the array and where condn true mark true else false
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
arr= arr[bool_index] #extracting true values
arr

array([12, 14, 16, 18, 20])