In [2]:
import numpy as np

In [3]:
#VALID SUDUKO
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [5]:
b=np.sum(s,axis=1) #row
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
b=np.sum(s,axis=0)
b  #VALID

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [8]:
#GENERAL QUESTIONS

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [9]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [13]:
#Find the average age of students.
c=data[:,0]
c
x=c.mean()
x

np.float64(18.4)

In [14]:
#Extract Math marks of all students.
z=data[:,1]
z

array([85, 92, 76, 65, 90])

In [15]:
#Find the highest Science mark.
science=data[:,2]
m=science.max()
m

np.int64(95)

In [19]:
#Get details of the student who scored more than 90 in Math.
z
b=z[z>90] #boolean indexing
b

array([92])

In [22]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [23]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [24]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)


array([86.6, 83.2])

In [42]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,1]>=80)]

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])